---
roles:
  - name: elliotweiser.osx-command-line-tools
    src: https://github.com/elliotweiser/ansible-osx-command-line-tools.git
    scm: git
  - name: geerlingguy.dotfiles
    source: https://github.com/geerlingguy/dotfiles.git
  - name: ansible-role-dock
    src: https://github.com/wayofdev/ansible-role-dock.git
    scm: git
    version: v2.3.0

collections:
  - name: community.general
    type: git
    source: https://github.com/ansible-collections/community.general.git
    version: 12.3.0
  - name: geerlingguy.mac
    type: git
    source: https://github.com/geerlingguy/ansible-collection-mac.git
    version: 5.0.0
  - name: wayofdev.macops
    type: git
    source: https://github.com/wayofdev/ansible-collection-macops.git
