
# Task: Copy AWS VM SSH keys to ~/.ssh/
# This task copies the AWS VM SSH keys from the specified source directory to the ~/.ssh/ directory on the target machine.
# The keys are copied with the specified owner, group, and mode permissions.
---
- name: Check if AWS VM SSH keys already exist
  ansible.builtin.stat:
    path: "{{ home_path }}/.ssh/{{ item }}"
  loop:
    - mford-useast-1-key.pem
    - mford-useast-2-key.pem
  register: aws_keys_stat

- name: Copy AWS VM SSH keys to ~/.ssh/ if not present
  ansible.builtin.copy:
    src: "{{ dropbox_local_path }}/My Documents/SSH Keys/AWS/{{ item.item }}"
    remote_src: true
    dest: "{{ home_path }}/.ssh/{{ item.item }}"
    owner: "{{ ansible_user }}"
    group: staff
    mode: '0600'
  loop: "{{ aws_keys_stat.results }}"
  when: not item.stat.exists

- name: Check if GCP VM SSH key exists
  ansible.builtin.stat:
    path: "{{ home_path }}/.ssh/michaelford85_github.pem"
  register: gcp_key_stat

- name: Copy GCP VM SSH key to ~/.ssh/ if not present
  ansible.builtin.copy:
    src: "{{ dropbox_local_path }}/My Documents/SSH Keys/Github/michaelford85/michaelford85_github.pem"
    remote_src: true
    dest: "{{ home_path }}/.ssh/michaelford85_github.pem"
    owner: "{{ ansible_user }}"
    group: staff
    mode: '0600'
  when: not gcp_key_stat.stat.exists

- name: Check if Home Lab SSH key exists
  ansible.builtin.stat:
    path: "{{ home_path }}/.ssh/fordlab.pem"
  register: home_lab_key_stat

- name: Copy Home Lab SSH key to ~/.ssh/ if not present
  ansible.builtin.copy:
    src: "{{ dropbox_local_path }}/My Documents/SSH Keys/Home Lab/fordlab.pem"
    remote_src: true
    dest: "{{ home_path }}/.ssh/fordlab.pem"
    owner: "{{ ansible_user }}"
    group: staff
    mode: '0600'
  when: not home_lab_key_stat.stat.exists

- name: Check if Github SSH Config file exists
  ansible.builtin.stat:
    path: "{{ home_path }}/.ssh/config"
  register: github_config_stat

- name: Copy Github SSH Config file to ~/.ssh/ if not present
  ansible.builtin.copy:
    src: "{{ dropbox_local_path }}/My Documents/SSH Keys/Github/config"
    remote_src: true
    dest: "{{ home_path }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: staff
    mode: '0600'
  when: not github_config_stat.stat.exists

- name: Test GitHub SSH authentication
  ansible.builtin.shell:
    cmd: "ssh -T git@github.com"
  register: github_ssh_test
  failed_when: >
    (github_ssh_test.rc != 1 and github_ssh_test.rc != 0) or
    ('successfully authenticated' not in github_ssh_test.stderr | lower)

- name: Display GitHub SSH authentication message
  ansible.builtin.debug:
    msg: "{{ github_ssh_test.stderr }}"