---
- name: Check if ~/venvs exists
  ansible.builtin.stat:
    path: "{{ home_path }}/venvs"
  register: venvs_dir_stat

- name: Create venvs directory if it does not exist
  ansible.builtin.file:
    path: "{{ home_path }}/venvs"
    state: directory
  when: not venvs_dir_stat.stat.exists

- name: Check if ansible venv exists
  ansible.builtin.stat:
    path: "{{ home_path }}/venvs/ansible"
  register: ansible_venv_stat

- name: Create ansible Virtual Environment if it does not exist
  ansible.builtin.shell:
    cmd: "python3 -m venv {{ home_path }}/venvs/ansible"
  when: not ansible_venv_stat.stat.exists

- name: Check if ansible-core is installed in the venv
  ansible.builtin.shell:
    cmd: "{{ home_path }}/venvs/ansible/bin/pip show ansible-core"
  register: ansible_core_check
  ignore_errors: true

- name: Install Ansible in the virtual environment if not present
  ansible.builtin.pip:
    name: ansible-core
    version: "{{ ansible_version_mac }}"
    virtualenv: "{{ home_path }}/venvs/ansible"
  when: ansible_core_check.rc != 0