---
- name: Create venvs directory
  ansible.builtin.file:
    path: "{{ home_path }}/venvs"
    state: directory

- name: Create ansible Virtual Environment
  ansible.builtin.shell:
    cmd: "python3 -m venv {{ home_path }}/venvs/ansible"

- name: Install Ansible in the virtual environment
  ansible.builtin.pip:
    name: ansible-core
    version: "{{ ansible_version_mac }}"
    virtualenv: "{{ home_path }}/venvs/ansible"
